server:
  port: 13100

spring:
  application:
    name: config-server
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yonggyo1125/spartahub_6th
          default-label: main
          search-paths:
            - configs/common
            - configs/{application}

#        native:
#          search-locations:
#            - classpath:/configs/common
#            - classpath:/configs/{application}



eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URL1:localhost}:13101/eureka/,http://${EUREKA_URL2:localhost}:13102/eureka/